"""create candidates table

Revision ID: e45d3ba74bb9
Revises: 
Create Date: 2026-07-14 22:40:23.644398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e45d3ba74bb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_notes', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
